# Khai bao thư viện

In [2]:
import pandas as pd
import numpy as np
print('Nhap du lieu thanh cong')

Nhap du lieu thanh cong

# Nhap du lieu

In [3]:
data = pd.read_csv('OnlineRetail.csv', header=0, encoding = 'ISO-8859-1')
display(data)
data.info()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

# 1. Tìm số hàng và số cột của dữ liệu
## Xuất ra theo dạng "Số hàng là xxx, số cột là yyy"

In [5]:
print('Số hàng là:', data.shape[0], ', Số cột là:', data.shape[1])

Số hàng là: 541909 , Số cột là: 8

# 2. Việt hóa tên các cột (có dấu)
**'So hoa don', 'Ma hang hoa', 'Mo ta', 'So luong', 'Ngay', 'Don gia', 'Ma KH'**

In [6]:
data.columns = ['Số hóa đơn', 'Mã hàng hóa', 'Mô tả', 'Số lượng', 'Ngày', 'Đơn giá', 'Mã KH', 'Quốc gia']
data

,Số hóa đơn,Mã hàng hóa,Mô tả,Số lượng,Ngày,Đơn giá,Mã KH,Quốc gia
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# 3. Thêm cột "Thành tiền" vào sau cuối, giá trị mặc định là 0

In [7]:
data['Thành tiền'] = 0
data

,Số hóa đơn,Mã hàng hóa,Mô tả,Số lượng,Ngày,Đơn giá,Mã KH,Quốc gia,Thành tiền
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,0
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,0
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,0
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,0
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,0
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,0
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,0

object (chu) > float > int > NaN

# 4. Thêm cột "Chiết khấu" sau cột "Đơn giá"
## Giá trị của cột "Chiết khấu" = 3 (đơn vị %)

In [8]:
data.insert(6, 'Chiết khấu (%)', 3)
data

,Số hóa đơn,Mã hàng hóa,Mô tả,Số lượng,Ngày,Đơn giá,Chiết khấu (%),Mã KH,Quốc gia,Thành tiền
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,3,17850.0,United Kingdom,0
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,3,17850.0,United Kingdom,0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,0
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,3,12680.0,France,0
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,3,12680.0,France,0
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,3,12680.0,France,0
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,0
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Số hóa đơn      541909 non-null  object
 1   Mã hàng hóa     541909 non-null  object
 2   Mô tả           540455 non-null  object
 3   Số lượng        541909 non-null  int64
 4   Ngày            541909 non-null  object
 5   Đơn giá         541909 non-null  float64
 6   Chiết khấu (%)  541909 non-null  int64
 7   Mã KH           406829 non-null  float64
 8   Quốc gia        541909 non-null  object
 9   Thành tiền      541909 non-null  int64
dtypes: float64(2), int64(3), object(5)
memory usage: 41.3+ MB

# 5. Thêm 1 sản phẩm sau hàng có index 541905
## Thông tin sp: 324345, 34534B, Noi chien khong dau, 1000, 23/6/2022 20:30, 50.2, 3, 312313.0, Vietnam, 0

In [11]:
data.loc[541905.5] = ['324345', '34534B', 'Noi chien khong dau', 1000, '23/6/2022 20:30', 50.2, 3, 312313.0, 'Vietnam', 0]
data = data.sort_index().reset_index(drop=True)
data

,Số hóa đơn,Mã hàng hóa,Mô tả,Số lượng,Ngày,Đơn giá,Chiết khấu (%),Mã KH,Quốc gia,Thành tiền
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,3,17850.0,United Kingdom,0
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,3,17850.0,United Kingdom,0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,0
...,...,...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,3,12680.0,France,0
541906,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,0
541907,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,3,12680.0,France,0
541908,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,0
541909,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,0

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   So hoa don      541909 non-null  object
 1   Ma hang hoa     541909 non-null  object
 2   Mo ta           540455 non-null  object
 3   So luong        541909 non-null  int64
 4   Ngay            541909 non-null  object
 5   Don gia         541909 non-null  float64
 6   Chiet khau (%)  541909 non-null  int64
 7   Ma KH           406829 non-null  float64
 8   Nuoc            541909 non-null  object
 9   Tien            0 non-null       float64
dtypes: float64(3), int64(2), object(5)
memory usage: 41.3+ MB

In [13]:
#Them san pham vao hang cuoi cung
data.loc[data.shape[0]]=['324345', '34534B', 'Noi chien khong dau', 1000, '23/6/2022 20:30', 50.2, 3, 312313.0, 'Vietnam', np.NaN]
display(data)

,So hoa don,Ma hang hoa,Mo ta,So luong,Ngay,Don gia,Chiet khau (%),Ma KH,Nuoc,Tien
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,3,17850.0,United Kingdom,NaN
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,NaN
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,3,17850.0,United Kingdom,NaN
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,NaN
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,NaN
...,...,...,...,...,...,...,...,...,...,...
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,3,12680.0,France,NaN
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,NaN
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,NaN
541909,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN
541910,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN

In [16]:
#Them san pham vao sau hang 541905
data.loc[541905.5]=['324345', '34534B', 'Noi chien khong dau', 3000, '25/6/2022 20:30', 50.2, 3, 312313.0, 'Vietnam', np.NaN]
data = data.sort_index().reset_index(drop=True)
display(data)

,So hoa don,Ma hang hoa,Mo ta,So luong,Ngay,Don gia,Chiet khau (%),Ma KH,Nuoc,Tien
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,3,17850.0,United Kingdom,NaN
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,NaN
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,3,17850.0,United Kingdom,NaN
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,NaN
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,NaN
...,...,...,...,...,...,...,...,...,...,...
541907,324345,34534B,Noi chien khong dau,2000,24/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN
541908,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,NaN
541909,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,NaN
541910,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN
541911,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN

In [17]:
data.tail(20)

,So hoa don,Ma hang hoa,Mo ta,So luong,Ngay,Don gia,Chiet khau (%),Ma KH,Nuoc,Tien
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,12/9/2011 12:49,8.95,3,13113.0,United Kingdom,NaN
541893,581586,20685,DOORMAT RED RETROSPOT,10,12/9/2011 12:49,7.08,3,13113.0,United Kingdom,NaN
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,12/9/2011 12:50,1.95,3,12680.0,France,NaN
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,12/9/2011 12:50,1.65,3,12680.0,France,NaN
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,12/9/2011 12:50,1.65,3,12680.0,France,NaN
541897,581587,22728,ALARM CLOCK BAKELIKE PINK,4,12/9/2011 12:50,3.75,3,12680.0,France,NaN
541898,581587,22727,ALARM CLOCK BAKELIKE RED,4,12/9/2011 12:50,3.75,3,12680.0,France,NaN
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,12/9/2011 12:50,3.75,3,12680.0,France,NaN
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,12/9/2011 12:50,3.75,3,12680.0,France,NaN
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,12/9/2011 12:50,1.95,3,12680.0,France,NaN
541902,581587,22629,SPACEBOY LUNCH BOX,12,12/9/2011 12:50,1.95,3,12680.0,France,NaN
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,12/9/2011 12:50,4.15,3,12680.0,France,NaN
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,3,12680.0,France,NaN
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,3,12680.0,France,NaN
541906,324345,34534B,Noi chien khong dau,3000,25/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN
541907,324345,34534B,Noi chien khong dau,2000,24/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN
541908,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,NaN
541909,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,NaN
541910,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN
541911,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,NaN

# 6. Tinh tien roi nhap gia tri vao cot 'Tien' theo cong thuc sau:
Tien = so luong x don gia x (100 - chiet khau (%))/100

In [12]:
data.loc[:,"Thành tiền"] = data.loc[:,"Số lượng"] * data.loc[:,"Đơn giá"] * (100 - data.loc[:,"Chiết khấu (%)"])/100
data

,Số hóa đơn,Mã hàng hóa,Mô tả,Số lượng,Ngày,Đơn giá,Chiết khấu (%),Mã KH,Quốc gia,Thành tiền
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,3,17850.0,United Kingdom,14.8410
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,19.7298
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,3,17850.0,United Kingdom,21.3400
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,19.7298
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,19.7298
...,...,...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,3,12680.0,France,12.2220
541906,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,48694.0000
541907,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,3,12680.0,France,16.1020
541908,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,16.1020
541909,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,14.4045

In [20]:
data['Tien'] = data['So luong']*data['Don gia']*(100-data['Chiet khau (%)'])/100
display(data)

,So hoa don,Ma hang hoa,Mo ta,So luong,Ngay,Don gia,Chiet khau (%),Ma KH,Nuoc,Tien
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,3,17850.0,United Kingdom,14.8410
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,19.7298
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,3,17850.0,United Kingdom,21.3400
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,19.7298
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,3,17850.0,United Kingdom,19.7298
...,...,...,...,...,...,...,...,...,...,...
541907,324345,34534B,Noi chien khong dau,2000,24/6/2022 20:30,50.20,3,312313.0,Vietnam,97388.0000
541908,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,3,12680.0,France,16.1020
541909,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,3,12680.0,France,14.4045
541910,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,48694.0000
541911,324345,34534B,Noi chien khong dau,1000,23/6/2022 20:30,50.20,3,312313.0,Vietnam,48694.0000

# 7. Luu du lieu ra file

df.to_excel('Tenfile.xlsx')

In [13]:
data.to_csv('Ketquahomnay.csv')
print('Xuat file thanh cong')

Xuat file thanh cong